Need to ensure supervise is done for cleanup.
o During delete of gearbox or gearbox-test-workers services, it does a
  "svc -dx" followed by "rm -rf" which fails occasionally (see below for
  details on rm -rf does not work always). To address this, a check if
  supervise is no longer running is added via the svok system call.
o If install is immediately followed by uninstall, cleanup fails
  sometimes since supervise has not started yet. In that case, we now
  wait for 5 secs to allow supervise to run.

Error seen from gearbox-svc-builder
rm: cannot remove `/var/gearbox/gearbox-workers/gearbox-sync-worker-04/log/supervise': Directory not empty
ERROR: rm -rf /var/gearbox/gearbox-workers/gearbox-sync-worker-04

$ rm -ri rmtest
rm: descend into directory `rmtest'? y
rm: remove directory `rmtest/foo'? y
rm: remove directory `rmtest/bar'? ^Z
[1]+  Stopped                 rm -ri rmtest
[EXIT 148] $ mkdir -p rmtest/baz
$ fg
rm -ri rmtest
y
rm: remove directory `rmtest'? y
rm: cannot remove `rmtest': Directory not empty
$

diff --git a/workers/gearbox/conf/init.d/gearbox-test-workers b/workers/gearbox/conf/init.d/gearbox-test-workers
--- a/workers/gearbox/conf/init.d/gearbox-test-workers
+++ b/workers/gearbox/conf/init.d/gearbox-test-workers
@@ -109,6 +109,15 @@ stop() {
 }
 
 delete() {
+    # check if services are in starting mode. We need to allow them to start
+    # completely for cleanup in delete operation
+    svstat /var/gearbox/test*-workers/* | grep "unable to open supervise" 2>&1 > /dev/null
+
+    # if any service is not created completely, we would wait for them to be created
+    if [[ $? -eq 0 ]]; then
+        action "Waiting for supervise to be spawned for new services" sleep 5
+    fi
+
     # Create an empty daemons json string
     echo '{ "daemons": [] }' > /tmp/empty-daemons.conf
 
